### ISSUE TITLE
error bestone while backtest

### ISSUE THREAD

**Issue by mhayta** [cloggy45/Gekko-Bot-Resources#12]
Its give this error,
Error: non-error thrown: Child process has died.
      at Object.onerror (/home/musa/gekko/node_modules/koa/lib/context.js:105:40)
      at process._tickCallback (internal/process/next_tick.js:109:7

**Comment by cloggy45** [comment]
more details of the back test please, what exchange? Currency pair?

**Comment by mhayta** [comment]
I've re install everythink and it's work properly. thanks...
