### ISSUE TITLE
error in console

### ISSUE THREAD

**Issue by shnmhrjn** [cloggy45/Gekko-Bot-Resources#14]
Whenever I run bestone strategy, I get error in console. what am I doing wrong?

  Error: non-error thrown:
  This Gekko instance encountered an error and can't continue
      at Object.onerror (C:\Users\sahan\Desktop\gekko2\gekko\node_modules\koa\lib\context.js:105:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

Hoping for fix soon, 

Regards,

**Comment by cloggy45** [comment]
What version of Gekko are you running it on?

**Comment by shnmhrjn** [comment]
@cloggy45  I found out that all the tulip based strategies were not working so I installed tulind and now it works . 

Thanks.
