### ISSUE TITLE
Installing broke gekko

### ISSUE THREAD

**Issue by regis456** [cloggy45/Gekko-Bot-Resources#16]
Please help I've been stuck on this for hours

At first I get this error:
`internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'moment'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/darthsyntax/gekko/core/util.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)`

If i try to `npm install moment` I get this. Which I can't fix for the life of me.

`/home/darthsyntax/gekko/core/util.js:56
    return util.getPackage().engines.node;
                                    ^

TypeError: Cannot read property 'node' of undefined
    at Object.getRequiredNodeVersion (/home/darthsyntax/gekko/core/util.js:56:37)
    at Object.recentNode (/home/darthsyntax/gekko/core/util.js:59:25)
    at Object.<anonymous> (/home/darthsyntax/gekko/core/util.js:180:10)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)`

**Comment by HOllarves** [comment]
Have you tried going to gekko's root folder and doing a `npm install`? It seems that you don't have the necessary dependencies to run gekko.

**Comment by regis456** [comment]
Naw I still get all of the same errors. It happened last time I tried to install this package after SirTificate's strategy.

**Comment by HOllarves** [comment]
I guess the best thing you could do is backup your strategies folder, delete gekko and do a fresh install. Just `git clone` de repo and do a `npm install`. Then you can reimport your strategies and install the needed dependencies for the specific strategy. Remember this dependencies should go in the project's root folder, not the strategy's. Hope it helps :)

**Comment by regis456** [comment]
I will repost if it doesn't :) Thanks!

**Comment by regis456** [comment]
I first installed gekko then before doing `npm install` I transferred the bot resources and ran `npm install` in both the gekko main folder and in gekko/exchange. And I am still getting this error: 

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'moment'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/darthsyntax/gekko/core/util.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by cloggy45** [comment]
@regis456 Looks like you're missing the `moment` dependency.
