### ISSUE TITLE
return util.getPackage().engines.node;

### ISSUE THREAD

**Issue by washingtonnuness** [cloggy45/Gekko-Bot-Resources#19]
root@Bot:/gekko# node gekko start

    ______   ________  __    __  __    __   ______
   /      \ /        |/  |  /  |/  |  /  | /      \
  /$$$$$$  |$$$$$$$$/ $$ | /$$/ $$ | /$$/ /$$$$$$  |
  $$ | _$$/ $$ |__    $$ |/$$/  $$ |/$$/  $$ |  $$ |
  $$ |/    |$$    |   $$  $$<   $$  $$<   $$ |  $$ |
  $$ |$$$$ |$$$$$/    $$$$$  \  $$$$$  \  $$ |  $$ |
  $$ \__$$ |$$ |_____ $$ |$$  \ $$ |$$  \ $$ \__$$ |
  $$    $$/ $$       |$$ | $$  |$$ | $$  |$$    $$/
   $$$$$$/  $$$$$$$$/ $$/   $$/ $$/   $$/  $$$$$$/

/gekko/core/util.js:56
    return util.getPackage().engines.node;
                                    ^

TypeError: Cannot read property 'node' of undefined
    at Object.getRequiredNodeVersion (/gekko/core/util.js:56:37)
    at Object.recentNode (/gekko/core/util.js:59:25)
    at Object.<anonymous> (/gekko/core/util.js:180:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
root@Bot:/gekko#

**Comment by cloggy45** [comment]
The new instructions address this issue.
