### ISSUE TITLE
After instalation i get;  module.js:550     throw err;

### ISSUE THREAD

**Issue by BKlun** [cloggy45/Gekko-Bot-Resources#20]
I have same issues ...

module.js:550
    throw err;
    ^

Error: Cannot find module 'moment'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/bklun/gekko/core/util.js:1:76)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)

i a kind of beginner so if you can type what i miseed or how to solve this mess..tnx..

**Comment by cloggy45** [comment]
Have you installed moment js?

**Comment by BKlun** [comment]
tnx..
i did not...but i will because id like to try this pack on win10. 
For now i manage to install Gekko  on Ubuntu platform...there were some issues with sqlite3 and nodejs versions...
